### ISSUE TITLE
notion d'objet n'est pas connue

### ISSUE THREAD

**Issue by YoungFrog** [asassoye/ESI-dev1-slides#2]
https://github.com/asassoye/ESI-dev1-slides/blob/839421b917ab4bf268444e812a49e769313c7e39/contents/theorie/declaration-et-creation/declaration-de-tableaux.tex#L22

attention, la notion de classe définissant un type n'est pas encore vraiment connue

**Comment by asassoye** [comment]
Oui je sais bien, mais il me paraissait logique de quand même le mentionner pour que par la suite on sache que nous pouvons crée des tableaux d'objets et qu'il n'est pas uniquement pour les types java. Vous préférez que je retire cette mention ou que je rajoute une phrase du type "Par la suite, quand nous créerons des classes, .."

**Comment by YoungFrog** [comment]
On connait déjà des types référence, principalement String. Je ferais donc l'exemple avec String, et mentionner qu'on pourra en créer d'autres nous-même.
